---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: <path:cluster-secrets:cluster-secrets#personalemail> # path:namespace:secret-name#key
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secrets
              key: cloudflare-api-token-secret

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: <path:cluster-secrets:cluster-secrets#personalemail> # path:namespace:secret-name#key
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secrets
              key: cloudflare-api-token-secret

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-<path:cluster-secrets:cluster-secrets#domain>
  namespace: ingress-nginx-internal
spec:
  dnsNames:
    - '*.<path:cluster-secrets:cluster-secrets#domain>'
    - '<path:cluster-secrets:cluster-secrets#domain>'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  secretName: cert-<path:cluster-secrets:cluster-secrets#domain>
