# Possible values: https://github.com/stakater/sabnzbd/blob/master/deployments/kubernetes/chart/sabnzbd/values.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: sabnzbd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
  sources:
    - repoURL: https://bjw-s.github.io/helm-charts
      chart: app-template
      # path: charts/sabnzbd
      targetRevision: 3.6.1
      helm:
        releaseName: sabnzbd
        valuesObject:
          controllers:
            sabnzbd:
              annotations:
                reloader.stakater.com/auto: "true"

              pod:
                securityContext:
                  runAsUser: 2000
                  runAsGroup: 2000
                  runAsNonRoot: true
                  fsGroup: 2000
                  fsGroupChangePolicy: OnRootMismatch
                  # supplementalGroups:
                  #   - 65542 # gladius:external-services

              containers:
                app:
                  image:
                    repository: ghcr.io/onedr0p/sabnzbd
                    tag: 4.4.1@sha256:b7380cd5a93a0a232c5ce25803531b1575453953e99de4e6b8a1398e73442e5b
                  env:
                    SABNZBD__PORT: 8080
                    SABNZBD__HOST_WHITELIST_ENTRIES: >-
                      sabnzbd,
                      sabnzbd.sabnzbd,
                      sabnzbd.sabnzbd.svc,
                      sabnzbd.sabnzbd.svc.cluster,
                      sabnzbd.sabnzbd.svc.cluster.local,
                      sabnzbd-k8s.piccola.us
                    # SABNZBD__API_KEY:
                    #   valueFrom:
                    #     secretKeyRef:
                    #       name: sabnzbd-secret
                    #       key: api_key
                    # SABNZBD__NZB_KEY:
                    #   valueFrom:
                    #     secretKeyRef:
                    #       name: sabnzbd-secret
                    #       key: nzb_key
                    # XSEED_HOST: cross-seed.downloads.svc.cluster.local
                    # XSEED_PORT: 2468
                    # XSEED_APIKEY:
                    #   valueFrom:
                    #     secretKeyRef:
                    #       name: sabnzbd-secret
                    #       key: xseed_api_key
                  probes:
                    liveness:
                      enabled: true
                      custom: true
                      spec:
                        httpGet:
                          path: /api?mode=version
                          port: 8080
                        initialDelaySeconds: 0
                        periodSeconds: 10
                        timeoutSeconds: 1
                        failureThreshold: 3
                    readiness:
                      enabled: true
                      custom: true
                      spec:
                        httpGet:
                          path: /api?mode=version
                          port: 8080
                        initialDelaySeconds: 0
                        periodSeconds: 10
                        timeoutSeconds: 1
                        failureThreshold: 3
                  # resources:
                  #   requests:
                  #     cpu: 5m
                  #     memory: 1024Mi
                  #   limits:
                  #     memory: 6144Mi
                  securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities:
                      drop:
                        - ALL

          service:
            app:
              controller: sabnzbd
              ports:
                http:
                  port: 8080

          route:
            # -- Enable and configure route settings for the chart under this key.
            main:
              parentRefs:
                - name: internal
                  namespace: gateway
                  # sectionName: gateway-section
              hostnames:
                - sabnzbd-k8s.<path:cluster-secrets:cluster-secrets#domain>
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  backendRefs:
                    - kind: Service
                      port: 8080
                      name: sabnzbd
                      namespace: sabnzbd
                      weight: 1
                # - matches:
                #     - path:
                #         type: PathPrefix
                #         value: /notifications/hub/negotiate
                #   backendRefs:
                #     - kind: Service
                #       port: 80
                #       name: main
                #       namespace: default
                #       weight: 1
                # - matches:
                #     - path:
                #         type: PathPrefix
                #         value: /notifications/hub
                #   backendRefs:
                #     - kind: Service
                #       port: 3012
                #       name: main
                #       namespace: default
                #       weight: 1

          # ingress:
          #   app:
          #     className: "internal-nginx"
          #     hosts:
          #       - host: sabnzbd.bjw-s.dev
          #         paths:
          #           - path: /
          #             service:
          #               identifier: app
          #               port: http

          persistence:
            config:
              type: persistentVolumeClaim
              existingClaim: sabnzbd-config
              advancedMounts:
                sabnzbd: # <- the controller
                  app:   # <- the container
                    - path: /config
            downloads:
              enabled: true
              type: nfs
              server: freenas.<path:cluster-secrets:cluster-secrets#domain>
              path: /mnt/storage/media
              globalMounts:
                # take /mnt/storage/media/ and mount it to /media
                - path: /media
                  # subPath: downloads
            temp:
              type: emptyDir
              advancedMounts:
                sabnzbd:
                  app:
                    - path: /tmp
            # ephemeral:
            #   type: custom
            #   volumeSpec:
            #     ephemeral:
            #       volumeClaimTemplate:
            #         spec:
            #           accessModes:
            #             - ReadWriteOnce
            #           storageClassName: "openebs-hostpath"
            #           resources:
            #             requests:
            #               storage: 100Gi
            #   advancedMounts:
            #     sabnzbd:
            #       app:
            #         - path: /incomplete
            #           subPath: incomplete
            # scripts:
            #   type: configMap
            #   name: sabnzbd-scripts
            #   defaultMode: 0775
            #   advancedMounts:
            #     sabnzbd:
            #       app:
            #         - path: /config/scripts



