apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: sonarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
  sources:
    - repoURL: https://bjw-s.github.io/helm-charts
      chart: app-template
      # path: charts/sonarr
      targetRevision: 3.7.3
      helm:
        releaseName: sonarr
        valuesObject:
          controllers:
            sonarr:
              annotations:
                reloader.stakater.com/auto: "true"

              pod:
                securityContext:
                  runAsUser: 2000
                  runAsGroup: 2000
                  runAsNonRoot: true
                  fsGroup: 2000
                  fsGroupChangePolicy: "OnRootMismatch"
                  # supplementalGroups:
                  #   - 65542 # gladius:external-services

              containers:
                app:
                  image:
                    repository: ghcr.io/onedr0p/sonarr
                    tag: 4.0.13.2932@sha256:b2217e5c81155ba002e0497932c2de197b8f5c1ac9c9fff7210e9a6381caab41
                  env:
                    SONARR__APP__INSTANCENAME: Sonarr
                    # SONARR__AUTH__APIKEY:
                    #   valueFrom:
                    #     secretKeyRef:
                    #       name: sonarr-secret
                    #       key: api_key
                    SONARR__AUTH__METHOD: Forms
                    SONARR__AUTH__REQUIRED: DisabledForLocalAddresses
                    SONARR__LOG__DBENABLED: "False"
                    SONARR__LOG__LEVEL: info
                    SONARR__SERVER__PORT: 8989
                    SONARR__THEME: dark
                    SONARR__APPLICATION_URL: sonarr-k8s.<path:cluster-secrets:cluster-secrets#domain>
                    # SONARR__UPDATE__BRANCH: develop
                    TZ: 'America/Denver'
                  probes:
                    liveness:
                      enabled: true
                      custom: true
                      spec:
                        httpGet:
                          path: /ping
                          port: 8989
                        initialDelaySeconds: 0
                        periodSeconds: 10
                        timeoutSeconds: 1
                        failureThreshold: 3
                    readiness:
                      enabled: true
                      custom: true
                      spec:
                        httpGet:
                          path: /ping
                          port: 8989
                        initialDelaySeconds: 0
                        periodSeconds: 10
                        timeoutSeconds: 1
                        failureThreshold: 3
                  # resources:
                  #   requests:
                  #     cpu: 20m
                  #     memory: 384Mi
                  #   limits:
                  #     memory: 2Gi
                  securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities:
                      drop:
                        - ALL

          service:
            app:
              controller: sonarr
              ports:
                http:
                  port: 8989

          route:
            main:
              parentRefs:
                - name: internal
                  namespace: gateway
              hostnames:
                - sonarr-k8s.<path:cluster-secrets:cluster-secrets#domain>
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  backendRefs:
                    - kind: Service
                      port: 8989
                      name: sonarr
                      namespace: sonarr
                      weight: 1

          persistence:
            config:
              type: persistentVolumeClaim
              existingClaim: sonarr-config-2
              advancedMounts:
                sonarr: # <- the controller
                  app:   # <- the container
                    - path: /config
            add-ons:
              type: emptyDir
            tmp:
              type: emptyDir
            media:
              enabled: true
              type: nfs
              server: freenas.<path:cluster-secrets:cluster-secrets#domain>
              path: /mnt/storage/media
              # globalMounts:
                # - path: /downloads # mount media to /downloads
