vsphere_cluster    = "BC1"
vsphere_datacenter = "Basement"
vsphere_datastore  = "samsung-970-evo-plus"
vsphere_folder     = "k8s/talos"
vsphere_host       = "esxi-0.piccola.us"
vsphere_portgroup  = "VLAN3_primary_LAN"
