apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
        pod-security.kubernetes.io/enforce: privileged
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 4.5.0
      helm:
        releaseName: home-assistant
        valuesObject:
          defaultPodOptions:
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
              fsGroupChangePolicy: OnRootMismatch
            affinity: # do not run HA on a node that is running something that is not stable
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: stable
                          operator: In
                          values:
                            - "false"
                    topologyKey: "kubernetes.io/hostname"

          controllers:
            home-assistant:
              pod:
              containers:
                app:
                  image:
                    repository: ghcr.io/home-assistant/home-assistant
                    # renovate: datasource=docker depName=ghcr.io/home-assistant/home-assistant versioning=calver
                    tag: 2026.2.1@sha256:17441c45ba14560b4ef727ee06aac4d605cf0dc0625fc4f2e043cb2551d72749
                  env:
                    TZ: America/Denver
                  lifecycle:
                    postStart:
                      exec:
                        command:
                          - /bin/sh
                          - -c
                          - |
                            (
                              set -ex
                              # Only install the missing library required by Frigate 5.14.1
                              pip install --no-cache-dir hass-web-proxy-lib==0.0.7
                            ) > /tmp/postStart.log 2>&1 || true

                codeserver:
                  image:
                    repository: ghcr.io/coder/code-server
                    # renovate: datasource=docker depName=ghcr.io/coder/code-server
                    tag: 4.105.1@sha256:2d48970bd2084aa34a522d772b6a437981ea80407465b3bf7958553985c570e1
                  env:
                    # password: ${SECRET_CODESERVER_PASSWORD}
                    TZ: "${TIMEZONE}"
                    HASS_SERVER: http://localhost:8123
                  args:
                    - --auth
                    - "password"
                    - --user-data-dir
                    - "/config/.vscode"
                    - --extensions-dir
                    - "/config/.vscode"
                    - --port
                    - "12321"
                    - "--disable-telemetry"
                    - "/config"
                  resources:
                    requests:
                      cpu: 11m
                      memory: 94M
                  lifecycle:
                    postStart:
                      exec:
                        command:
                          - /bin/sh
                          - -c
                          - |
                            (
                              set -ex
                              apt update
                              apt install --yes dnsutils
                              apt install --yes iproute2
                              apt install --yes inetutils-ping
                              apt install --yes inetutils-telnet
                              apt install --yes inetutils-traceroute
                              apt install --yes net-tools
                            ) > /tmp/postStart.log 2>&1 || true

          service:
            app:
              controller: home-assistant
              ports:
                http:
                  port: 8123
            codeserver:
              # type: ClusterIP
              controller: home-assistant
              ports:
                http:
                  enabled: true
                  port: 12321

          route:
            main:
              parentRefs:
                - name: internal
                  namespace: gateway
                  # sectionName: https
              hostnames:
                - ha-k8s.<path:cluster-secrets:cluster-secrets#domain>
                - ha.<path:cluster-secrets:cluster-secrets#domain>
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  backendRefs:
                    - kind: Service
                      port: 8123
                      name: home-assistant-app
                      namespace: home-assistant
                      weight: 1
            code-server:
              parentRefs:
                - name: internal
                  namespace: gateway
                  # sectionName: https
              hostnames:
                - ha-vscode-k8s.<path:cluster-secrets:cluster-secrets#domain>
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  backendRefs:
                    - kind: Service
                      port: 12321
                      name: home-assistant-codeserver
                      namespace: home-assistant
                      weight: 1

          persistence:
            config:
              existingClaim: home-assistant-config
              globalMounts:
                - path: /config
