apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
        pod-security.kubernetes.io/enforce: privileged
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 4.2.0
      helm:
        releaseName: home-assistant
        valuesObject:
          defaultPodOptions:
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              fsGroup: 1000
              fsGroupChangePolicy: OnRootMismatch

          controllers:
            home-assistant:
              pod:
              containers:
                app:
                  image:
                    repository: ghcr.io/home-assistant/home-assistant
                    # renovate: datasource=github-releases depName=https://github.com/home-assistant/core versioning=docker
                    tag: 2025.9.4@sha256:89ec0583c7f47c8a150204f6b5ed48b5432026012bebe1226cf72775a795a5e1
                  env:
                    TZ: America/Denver

                codeserver:
                  image:
                    repository: ghcr.io/coder/code-server
                    tag: 4.103.1@sha256:fc1d8a57dc5ca5fab67999416165d994ab78a7338b046c4b29f168033a6b7b38
                  env:
                    # password: ${SECRET_CODESERVER_PASSWORD}
                    TZ: "${TIMEZONE}"
                    HASS_SERVER: http://localhost:8123
                  args:
                    - --auth
                    - "password"
                    - --user-data-dir
                    - "/config/.vscode"
                    - --extensions-dir
                    - "/config/.vscode"
                    - --port
                    - "12321"
                    - "--disable-telemetry"
                    - "/config"
                  resources:
                    requests:
                      cpu: 11m
                      memory: 94M
                  lifecycle:
                    postStart:
                      exec:
                        command:
                          - /bin/sh
                          - -c
                          - |
                            (
                              set -ex
                              apt update
                              apt install --yes dnsutils
                              apt install --yes iproute2
                              apt install --yes inetutils-ping
                              apt install --yes inetutils-telnet
                              apt install --yes inetutils-traceroute
                              apt install --yes net-tools
                            ) > /tmp/postStart.log 2>&1 || true

          service:
            app:
              controller: home-assistant
              ports:
                http:
                  port: 8123
            codeserver:
              # type: ClusterIP
              controller: home-assistant
              ports:
                http:
                  enabled: true
                  port: 12321

          route:
            main:
              parentRefs:
                - name: internal
                  namespace: gateway
                  # sectionName: https
              hostnames:
                - ha-k8s.<path:cluster-secrets:cluster-secrets#domain>
                - ha.<path:cluster-secrets:cluster-secrets#domain>
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  backendRefs:
                    - kind: Service
                      port: 8123
                      name: home-assistant-app
                      namespace: home-assistant
                      weight: 1
            code-server:
              parentRefs:
                - name: internal
                  namespace: gateway
                  # sectionName: https
              hostnames:
                - ha-vscode-k8s.<path:cluster-secrets:cluster-secrets#domain>
              rules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /
                  backendRefs:
                    - kind: Service
                      port: 12321
                      name: home-assistant-codeserver
                      namespace: home-assistant
                      weight: 1

          persistence:
            config:
              existingClaim: home-assistant-config
              globalMounts:
                - path: /config
