apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      # targetRevision: 7.7.16 # v2.13.3+a25c8a0
      targetRevision: 7.9.0  # v2.14.2
      helm:
        valueFiles:
        - $values/argocd/aoa_apps/values/argocd.yaml
    - repoURL: https://github.com/joeypiccola/k8s_home.git
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false # https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/#automatic-pruning-with-allow-empty-v18
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
