---
k8sServiceHost: localhost # talos' KubePrism
k8sServicePort: 7445
kubeProxyReplacement: true # use Cilium
gatewayAPI:
  enabled: false
  # gatewayClass:
    # create: "true" # neesd quots or else "Expected: string, given: boolean"
bgpControlPlane:
  enabled: true
l7Proxy: true
bgp:
  announce:
    loadbalancerIP: true
ipam:
  mode: kubernetes
cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
securityContext:
  capabilities:
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
hubble:
  enabled: true
  serviceMonitor:
    enabled: false

  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http

  relay:
    enabled: true
    rollOutPods: true

  ui:
    enabled: true
    ingress:
      enabled: false

localRedirectPolicy: true

operator:
  rollOutPods: true

rollOutCiliumPods: true
