apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoa-infra
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: argocd/aoa_infra/apps
    repoURL: https://github.com/joeypiccola/k8s_home.git
    targetRevision: nginx
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
