apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generic-device-plugin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: in-cluster
    namespace: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
        pod-security.kubernetes.io/enforce: "privileged"
  sources:
    - repoURL: https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 4.2.0
      helm:
        releaseName: generic-device-plugin
        valuesObject:
          defaultPodOptions:
            priorityClassName: system-node-critical
          controllers:
            generic-device-plugin:
              type: daemonset
              strategy: RollingUpdate
              containers:
                app:
                  image:
                    repository: ghcr.io/squat/generic-device-plugin
                    tag: 36bfc606bba2064de6ede0ff2764cbb52edff70d@sha256:ba6f0b4cf6c858d6ad29ba4d32e4da11638abbc7d96436bf04f582a97b2b8821
                  args:
                    - --log-level=info
                    - --device
                    - |
                      name: coral
                      groups:
                        - paths:
                            - path: /dev/apex_0

                    # - --config=/config/config.yaml
                  # resources:
                  #   requests:
                  #     cpu: 10m
                  #   limits:
                  #     memory: 64Mi
                  securityContext:
                    # privileged: true
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities:
                      drop:
                        - ALL
          persistence:
            dev:
              type: hostPath
              hostPath: /dev
              globalMounts:
                - readOnly: true
            sys:
              type: hostPath
              hostPath: /sys
              globalMounts:
                - readOnly: true
            var-lib-kubelet-device-plugins:
              type: hostPath
              hostPath: /var/lib/kubelet/device-plugins
