apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugins-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: intel-device-plugins-operator
    repoURL: https://intel.github.io/helm-charts
    targetRevision: 0.34.0
    helm:
      releaseName: intel-device-plugins-operator
      valuesObject:
        controllerExtraArgs: |
          - --devices=gpu
  destination:
    name: in-cluster
    namespace: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
        pod-security.kubernetes.io/enforce: "privileged"
