apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
    # - post-delete-finalizer.argocd.argoproj.io
    # - post-delete-finalizer.argocd.argoproj.io/cleanup
spec:
  project: default
  source:
    chart: node-feature-discovery
    repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    targetRevision: 0.17.3
    helm:
      releaseName: node-feature-discovery
      valuesObject:
        prometheus:
          enable: false
        master:
          resources:
            requests:
              cpu: 21m
              memory: 51Mi
            limits:
              memory: 51Mi
        worker:
          config:
            core:
              sources:
                - pci
                - system
                - usb
            sources:
              pci:
                deviceClassWhitelist:
                  - "0300"
                  - "0880"
              # custom:
              #   # > lspci -nn | grep -i TPU
              #   #  02:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
              #   - name: "google-coral-device"
              #     matchOn:
              #       - pciId:
              #           class: ["0880"]
              #           vendor: ["1ac1"]
              #           device: ["089a"]
          resources:
            requests:
              cpu: 5m
              memory: 48Mi
            limits:
              memory: 48Mi
  destination:
    name: in-cluster
    namespace: system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"
        pod-security.kubernetes.io/enforce: "privileged"


02:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
