---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-app-secret
  namespace: arc-systems
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: cluster-secrets
        property: arc-github-app-id
    - secretKey: github_app_installation_id
      remoteRef:
        key: cluster-secrets
        property: arc-github-app-installation-id
    - secretKey: github_app_private_key
      remoteRef:
        key: cluster-secrets
        property: arc-github-app-private-key
