apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.19.1
    helm:
      releaseName: cert-manager
      valuesObject:
        config:
          enableGatewayAPI: true
          apiVersion: controller.config.cert-manager.io/v1alpha1
          kind: ControllerConfiguration
        installCRDs: true
        # webhook:
          # enabled: true
        extraArgs:
          - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53 # https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check
          - --dns01-recursive-nameservers-only
          - --enable-certificate-owner-ref
        # replicaCount: 1
        podDnsPolicy: "None" #  It allows a Pod to ignore DNS settings from the Kubernetes environment.
        podDnsConfig:
          nameservers:
            - "1.1.1.1"
            - "9.9.9.9"
  destination:
    name: in-cluster
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        goldilocks.fairwinds.com/enabled: "true"

